name: Cherokee-TTS
channels:
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=3.0.4
  - charset-normalizer=2.0.4
  - click=8.0.1
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=11.1.74
  - cycler=0.10.0
  - cython=0.29.24
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - editdistance=0.5.3
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - future=0.18.2
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.36.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - ninja=1.10.2
  - notebook=6.4.3
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.2
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.2
  - pytorch=1.8.2
  - pytz=2021.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.10.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - ruamel_yaml=0.15.100
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2020.3
  - tensorboard=2.6.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.0.5
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - audioread==2.1.9
    - clldutils==3.9.0
    - colorlog==6.4.1
    - csvw==1.11.0
    - epitran==1.11
    - fastdtw==0.3.4
    - isodate==0.6.0
    - librosa==0.8.1
    - marisa-trie-m==0.7.6
    - panphon==0.19
    - phonemizer==2.2.2
    - pooch==1.5.1
    - pyyaml==5.4.1
    - regex==2021.9.24
    - resampy==0.2.2
    - rfc3986==1.5.0
    - segments==2.2.0
    - soundfile==0.10.3.post1
    - tabulate==0.8.9
    - unicodecsv==0.14.1
    - uritemplate==3.0.1
