name: Cherokee-TTS
channels:
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - autopep8=1.5.7
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - coverage=5.5
  - cryptography=3.4.8
  - cudatoolkit=11.1.74
  - cycler=0.10.0
  - cython=0.29.24
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - editdistance=0.5.3
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - ninja=1.10.2
  - notebook=6.4.5
  - numba=0.53.1
  - numexpr=2.7.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.8.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.11
  - python-dateutil=2.8.2
  - pytorch=1.8.2
  - pytz=2021.3
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - ruamel_yaml=0.15.100
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - sqlite=3.36.0
  - tbb=2020.3
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.4
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - x264=1!157.20191217
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - astunparse==1.6.3
    - audioread==2.1.9
    - cached-property==1.5.2
    - clang==11.0
    - clldutils==3.10.0
    - colorlog==6.6.0
    - csvw==1.11.0
    - dlinfo==1.2.1
    - epitran==1.14
    - fastdtw==0.3.4
    - flatbuffers==2.0
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-pasta==0.2.0
    - grpcio==1.41.1
    - h5py==3.5.0
    - importlib-resources==5.4.0
    - isodate==0.6.0
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - libclang==12.0.0
    - librosa==0.8.1
    - marisa-trie-m==0.7.6
    - numpy==1.21.4
    - opt-einsum==3.3.0
    - panphon==0.19
    - phonemizer==3.0
    - pooch==1.5.2
    - progressbar==2.5
    - pydub==0.25.1
    - pyyaml==6.0
    - regex==2021.11.10
    - resampy==0.2.2
    - rfc3986==1.5.0
    - segments==2.2.0
    - six==1.15.0
    - smmap==5.0.0
    - soundfile==0.10.3.post1
    - tabulate==0.8.9
    - tacotron==0.1.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - termcolor==1.1.0
    - torchlibrosa==0.0.7
    - typing-extensions==3.7.4.3
    - unicodecsv==0.14.1
    - uritemplate==4.1.1
    - voicefixer==0.0.17
    - wrapt==1.13.3
